---
title: "Analysis.Rmd"
output: pdf_document
date: "2023-06-20"
---

```{r}
library(readxl)
library(writexl)

# Read the breast methylation data
breast_meth <- read_excel("C:/Users/mar32128/Documents/Doc/Data_science/breast_meth_subset_new.xlsx")

breast_meth <-as.data.frame(breast_meth)

# Read the radiation data
rad <- read_excel("C:/Users/mar32128/Downloads/lung/Radiation_clinical.xlsx")

# Remove the last character from each row name in the radiation data
rad$SAMPLE <- substr(rad$SAMPLE, 1, nchar(rad$SAMPLE) - 1)

rad <-as.data.frame(rad)


```


 
```{r}
 
# merge both tables together to filter all breast data from the radiation table
subset_df <- rad[rad$SAMPLE %in% breast_meth$...1, ]

 # write the breast data in a new table
write_xlsx(subset_df, "breast_radiation_subset.xlsx")

```


```{r}

library(ggplot2)
library(dplyr)
library(GGally)


# Explore the structure and summary of the data
summary(subset_df)

# Perform data visualization with different Plots using ggpairs to understand the dependencies between variables

ggpairs(data = subset_df , columns = c("RADIATION RESPONSE", "RADIATION CLASS", "AGE", "GENDER", "RACE","HISTOLOGY" ), axisLabels = "show", mapping = aes(color = "red")) + theme(axis.text.x = element_text(size = 8, angle = 60, hjust = 1)) + theme(axis.text.y = element_text(size = 3, angle = 0, hjust = 0))



```

